### ISSUE TITLE
CI/CD online

### ISSUE THREAD

**Issue by Piiit** [noi-techpark/it.bz.noi.community.ios#1] opened 2021-07-21 19:23 UTC
High Priority. Deadline: 15 September 2021

As a NOI App developer I want to have the CI/CD infrastructure online in order to be faster in the release and test of new versions of the app

- [x] Dimension provides a hello-world to get started with the pipelines
- [x] NOI creates a CI pipeline with public feedback logs
- [x] I asked Dimension to provide some Fastlane scripts or manual build instructions, which will then be used to finalize the pipeline <-- @matax87 could you please help me on this? I had some problems here... without a Mac it is not easy to debug... thx
- [x] Dimension and NOI creates a CD pipeline to build and push the app to a test channel
  - [x] We need to decide how to handle code signing and provisioning profiles
  - [x] Finalize the pipeline, that is build and archive the build artifacts
  - [x] push it to testflight on each snapshot release (that is when we tag a commit with `v1.2.3-snapshot` for example)
- [x] Update the pipeline that on CI it only run tests
- [x] Update the pipeline that on CD it uploads it to testflight, when it is merged into development... we need to always increment the build number
- [ ] Write documentation and provide scripts for each step

@matax87 comes back from holidays the 13 Sep, lets wait for him to conclude this work --> DONE

**Comment by Piiit** [comment] 2021-08-12 18:12
@matax87 I move this user story back to "TO DO" for the documentation and/or fastlane scripts... thx

**Comment by matax87** [comment] 2021-08-13 06:59
@Piiit Provisioning profiles can be created on App Store connect and download each time by fastlane when needed. For code signing Fastlane's match (https://codesigning.guide) may solve the problem.
When provisioning profiles and code signing are solved I'm going to provide fastlane lanes (scripts) for CD.
Please note that fastlane requires Ruby versions 2.5 or newer. We usually use https://github.com/rbenv/rbenv and fastlane as gem via bundle with a step in the pipeline to install the ruby version required by the project, gem and bundle and fastlane.

**Comment by Piiit** [comment] 2021-08-13 08:51
@matax87 We have a signing certificate and provisioning profiles already... that was not the problem. The problem was for me to use them correctly via xcodebuild from the command line. So please just send fastlane and related scripts. Those scripts should be as complete as possible, with some documentation which code signing type you use etc. If you have some gitlab ci scripts or bash or dockerfile scripts to install your build system would also be of great help. So we can migrate them to github actions. The more we get the easier it will be to figure out what's missing.

Thanks for your help in this!

**Comment by Piiit** [comment] 2021-08-13 08:53
@sseppi I invited Alex to this party, to continue the pipeline scripts on github actions after Dimension provides some documentation and scripts used for building, testing, and deployment to the testing channels. Releasing the app will be postponed until we have some real functionality implemented, currently we have only "hello worlds" in ios and android.

 All this is, due to my absence the next two weeks.

**Comment by matax87** [comment] 2021-08-13 09:25
> @matax87 We have a signing certificate and provisioning profiles already... that was not the problem. The problem was for me to use them correctly via xcodebuild from the command line. So please just send fastlane and related scripts. Those scripts should be as complete as possible, with some documentation which code signing type you use etc. If you have some gitlab ci scripts or bash or dockerfile scripts to install your build system would also be of great help. So we can migrate them to github actions. The more we get the easier it will be to figure out what's missing.
> 
> Thanks for your help in this!

The problem is that fastlane needs access both to provisioning profiles and the certificates (also to the private keys) in order to sign the app. The former can be download each time by fastlane from App Store connect, but the same approach cannot be done for the latter. Is not secure to include these files in the repository; thus, this is a problem that needs to be solved before proceeding with fastlane scripts.

Please take a look to https://docs.fastlane.tools/codesigning/getting-started/.
Me and @macteo are available to discuss it and/or suggest viable solutions in a call-meeting.

**Comment by Piiit** [comment] 2021-09-16 06:01
@alexlanz Dimension and I did this in a pair programming session, so I remove it from your Kanban

**Comment by Piiit** [comment] 2021-09-16 06:06
@matax87 @macteo 
To upload it to testflight, we need to update the build number each time... Question is, should we do this on each push to the "development" branch or only if the commit gets tagged in a certain way? Is there a good way to automatically increment the build number?

**Comment by Piiit** [comment] 2021-09-16 06:16
Another question: Should we do the Export .ipa step in the CI or only during CD?

**Comment by matax87** [comment] 2021-09-16 07:51
@Piiit usually our CD pipelines are triggered only on a particular branch (`master` / `main` we follow git-flow's conventions). We change the version (e.g. 1.0.0) when needed and increment the build number (e.g. 42) manually.

The archive, export IPA, upload IPA to TestFlight steps are only needed for CD and not for CI.

**Comment by matax87** [comment] 2021-09-16 07:55
@Piiit I don't see any entry on TestFlight. The build number must change each time but not for the first upload. Shall we try at least to do the first upload to TestFlight, in order to verify the correctness of the export IPA step?

Thank you.

**Comment by Piiit** [comment] 2021-09-16 09:23
OK, lets do the increment and testflight release manually for now, and maybe we see what we can do in the future... if we push that then to the development branch it should be published to the store...

I changed the action now, that it only triggers regular tests during CI, nothing else...
It would be nice to have another short pair programming session, I write you a mail

**Comment by macteo** [comment] 2021-09-16 10:20
> Is there a good way to automatically increment the build number?
Based on my opinion, no.

There are different automatic options and the manual one:
- Add a post commit git hook that bumps the build number. However working on different branches and with different persons will inevitably cause conflicts.
- Add a step on the CD that bumps the version, however this won’t be saved back on the project, as usually it’s not recommended, maybe even not possible on GitHub actions, to commit and push from the pipelines. 
- Manually bump the version as required on specific branches (usually `releases/v1.2.3`).

I would suggest to only activate the CD pipeline on commits in the `master` branch, after a `release/` branch is merged. In alternative the CD can be triggered only on commits on the `release/` branches instead of master.
The advantage to run the pipelines on `master` can be used also to avoid unauthorized commits if the master branch itself is protected with proper ACL.

**Closed** 2021-11-23 13:49 UTC
Labels: prj:noiapp
